### ISSUE TITLE
Doesn't work currectly in Firefox

### ISSUE THREAD

**Issue by filips123** [theodesp/codethat#1]
The website doesn't work correctly in Firefox. The header is too small so some text overlaps and overflows.

![screenshot](https://user-images.githubusercontent.com/16626308/59567373-88a72080-906d-11e9-864b-d18de15c1224.png)

**Comment by theodesp** [comment]
Thank you for the feedback. Probably I forgot to add some classes during the conversion. I will push some fixes today.
